# Определение команды удаления и расширение файла в зависимости от ОС
RM=del


l517194o= dfs.o graph.o
dfs.exe: $(l517194o)
	$(CXX) -o dfs.exe $(l517194o)

dfs.o: dfs.cpp
	$(CXX) -c dfs.cpp

# Компиляция graph.o
graph.o: ../graph.cpp
	$(CXX) -c ../graph.cpp
